### ISSUE TITLE
Export to codepen fails

### ISSUE THREAD

**Issue by KnisterPeter** [vsls-contrib/gistpad#84] opened 2020-01-02 09:42 UTC
For me the 'export to codepen' command fails with the following message:
`Error running command gistpad.exportGistToCodePen: Unexpected token < in JSON at position 5. This is likely caused by the extension that contributes gistpad.exportGistToCodePen.`

Unfortunatelly there is no stacktrace or further info.

The setup of my gistpad is: windows 10 and working with github enterprise

**Comment by lostintangent** [comment] 2020-01-02 15:49
Thanks for reporting this! Would you be able to share the gist that you encounter this error on? If you right-click the gist in the `Gists` tree and select `Copy GitHub URL`, you could paste that here and I could take a look at exactly what's going on. Thanks!

**Comment by KnisterPeter** [comment] 2020-01-02 16:00
The basic problem is that the gist is in our github enterpise, so its not shareable.
I could try to create a gist in public github and then to share that. Maybe it has the same problem.

**Comment by lostintangent** [comment] 2020-01-02 16:18
Ah OK, good point. Could you expand the playground, open the playground.json file and then paste it’s contents here (that’s simply the playground metadata file)? I suspect the issue is with that file being invalid JSON, and it fails when I try to parse it.

**Comment by KnisterPeter** [comment] 2020-01-02 16:23
Sure,
the `playground.json` looks like this:
```json
{
  "scripts": [
    "react",
    "react-dom"
  ],
  "styles": []
}
```
I've discovered a wired effect in vscode. Its possible to load all the gists in the treeview but when I want to open a file, some of them contain the html from github enterprise for a logged out user.
Are the files cached in vscode? The strange thing is that API calls seems to work, otherwise the tree view should be empty.

I've already relogged in and reloaded vscode. The gistpad output panel states that I'm logged in.

**Comment by lostintangent** [comment] 2020-01-02 16:42
Hmm, yeah that `playground.json` file obviously looks valid. If you right-click that gist and select `Open Gist Files`, does the playground appear to work correctly? And so aside from the auth issue, you only seeing this error when trying to export to CodePen?

**Comment by lostintangent** [comment] 2020-01-02 16:56
Actually, as I think about this, the export is going to fail even if this issue is fixed. The CodePen export page that is launched needs to be able to read the gist data, which it wouldn't be able to in the case of a GH enterprise-hosted gist. So I may need disable this menu for GHE users until I make this work.

**Comment by KnisterPeter** [comment] 2020-01-03 08:17
> Hmm, yeah that `playground.json` file obviously looks valid. If you right-click that gist and select `Open Gist Files`, does the playground appear to work correctly? And so aside from the auth issue, you only seeing this error when trying to export to CodePen?

No, half of the files are okay, the other half not. After restart things change, other files are valid... Maybe its a problem with our github instance.

**Comment by lostintangent** [comment] 2020-11-24 22:54
I'm closing this issue since I'm about to replace the token flow with VS Code's new integrated auth support. Unfortunately, that doesn't support GitHub Enterprise yet, and so I'm going to consider GHE unsupported until VS Code adds support for it.

**Closed by lostintangent** 2020-11-24 22:54 UTC
Labels: area: codepen, area: ghe, area: playgrounds, bug
