### ISSUE TITLE
Tag interface

### ISSUE THREAD

**Issue by majkinetor** [vsls-contrib/gistpad#107] opened 2020-01-15 07:40 UTC
Several system add tags to gist descriptions. My current favorite is https://gistlist.ksdev.pl:

Screen:

![image](https://user-images.githubusercontent.com/85767/72414264-1e28a100-3772-11ea-9ee2-97dedf5377b1.png)

The same thing in vscode:

![image](https://user-images.githubusercontent.com/85767/72414365-54662080-3772-11ea-901b-99d5366ea661.png)

Gistpad could make some or all of the following features on tags:

1. Clickable. The same as in gistlist, once you click it, only relevant gists with that tags are shown.
2. Searchable. For example search box on top of existing intervace.
3. Sortable by tags.

I think this is easy to implement and certainly is compatibile with number of other systems.

Resolves also: #95, #7

**Comment by lostintangent** [comment] 2020-02-22 22:05
Thanks! I'm going to close this as a duplicate of #7.

**Closed by lostintangent** 2020-02-22 22:05 UTC
