### ISSUE TITLE
can't view starred gists

### ISSUE THREAD

**Issue by keegoid** [vsls-contrib/gistpad#83] opened 2020-01-01 00:49 UTC
gistpad gives an error when I try to view my starred gists: "cannot read property 'login' of undefined".
I've created a personal access token with gists checked and logged in using that token.

![Screenshot from 2019-12-31 16-43-30](https://user-images.githubusercontent.com/4400306/71636960-60d47000-2bed-11ea-8a4a-36289a0afeca.png)

Regards,
Keegan

**Comment by lostintangent** [comment] 2020-01-01 02:08
Thanks for reporting this! Do you see this error when trying to expand the starred gists node in the tree? I’ll try to look into what might be happening. Apologies for the issue!

**Comment by keegoid** [comment] 2020-01-01 03:47
Yes, it happens both when I click on Starred Gists in the tree and also when I choose that options from the command palette. Reading, editing, and creating gists seems to be working. Just the starred section is not. But don't work on it tonight. Happy New Year!

**Comment by lostintangent** [comment] 2020-01-01 06:33
Aha! The issue is that I didn't account for anonymous gists, since they've been deprecated for so long. But you had [one starred gist, that is anonymous](https://gist.github.com/anonymous/6bebae3eb9f7b972e6f0), and therefore, when the extension tries to access the owner of that gist, it fails. I'll release a fix for this tomorrow. Thanks again for reporting this!

**Comment by lostintangent** [comment] 2020-01-02 21:32
The fix for this has been shipped to the marketplace, so if you update your GistPad extension, you should be good to go 👍 Let me know if you run into any other problems. Thanks!

**Closed by lostintangent** 2020-01-02 21:32 UTC

**Comment by keegoid** [comment] 2020-01-02 23:50
Good work and thank you. It is working now.
